/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useRef } from "react";

export function Hero(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Monkey06.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Defaults" scale={2.662}>
          <group name="SALLY">
            <skinnedMesh
              castShadow
              receiveShadow
              name="Cube002"
              geometry={nodes.Cube002.geometry}
              material={materials.body}
              skeleton={nodes.Cube002.skeleton}
            />
            <skinnedMesh
              castShadow
              receiveShadow
              name="Cube002_1"
              geometry={nodes.Cube002_1.geometry}
              material={materials.EYES}
              skeleton={nodes.Cube002_1.skeleton}
            />
          </group>
          <primitive object={nodes.spine} />
          <primitive object={nodes.handikL} />
          <primitive object={nodes.upper_arm_targetL} />
          <primitive object={nodes.handikR} />
          <primitive object={nodes.upper_arm_targetR} />
          <primitive object={nodes.footikL} />
          <primitive object={nodes.polelegL} />
          <primitive object={nodes.footikR} />
          <primitive object={nodes.polelegR} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Monkey06.glb");
