/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Make Joke Horror Official (https://sketchfab.com/MakeJokeHorror)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/king-kong-animated-2b7ce05ebe4c47178b30e18dd334ede5
Title: King Kong animated
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useRef } from "react";

export function Mechant(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./Mechant01.glb");
  const { actions } = useAnimations(animations, group);
  console.log(actions);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="king_kongqc_skeleton_93">
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.King_Kong_D}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.King_Kong_Fur}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <skinnedMesh
                    name="Object_10"
                    geometry={nodes.Object_10.geometry}
                    material={materials.King_Kong_Fur}
                    skeleton={nodes.Object_10.skeleton}
                  />
                  <skinnedMesh
                    name="Object_12"
                    geometry={nodes.Object_12.geometry}
                    material={materials.King_Kong_Fur}
                    skeleton={nodes.Object_12.skeleton}
                  />
                  <skinnedMesh
                    name="Object_14"
                    geometry={nodes.Object_14.geometry}
                    material={materials.King_Kong_Fur}
                    skeleton={nodes.Object_14.skeleton}
                  />
                  <skinnedMesh
                    name="Object_16"
                    geometry={nodes.Object_16.geometry}
                    material={materials.King_Kong_Fur}
                    skeleton={nodes.Object_16.skeleton}
                  />
                  <skinnedMesh
                    name="Object_18"
                    geometry={nodes.Object_18.geometry}
                    material={materials.King_Kong_Fur}
                    skeleton={nodes.Object_18.skeleton}
                  />
                  <skinnedMesh
                    name="Object_20"
                    geometry={nodes.Object_20.geometry}
                    material={materials.King_Kong_Arms_D}
                    skeleton={nodes.Object_20.skeleton}
                  />
                  <skinnedMesh
                    name="Object_21"
                    geometry={nodes.Object_21.geometry}
                    material={materials.King_Kong_D}
                    skeleton={nodes.Object_21.skeleton}
                  />
                  <group name="body1_model0_86" />
                  <group name="body2_model0_87" />
                  <group name="body3_model0_88" />
                  <group name="body4_model0_89" />
                  <group name="body5_model0_90" />
                  <group name="body6_model0_91" />
                  <group name="King_Kong_Legendary_2021_92" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./Mechant01.glb");
