/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: michael_grodkowski (https://sketchfab.com/michael_grodkowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/a-fantasy-tree-bc7547be2e554125b3917bd2b80b8866
Title: A fantasy tree
*/

import { useGLTF } from "@react-three/drei";

export function Tree(props) {
  const { nodes, materials } = useGLTF("./Tree01.glb");
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.pPlane156_lambert2_0.geometry} material={materials.lambert2} />
      <mesh castShadow receiveShadow geometry={nodes.pPlane156_lambert1_0.geometry} material={materials.lambert1} />
    </group>
  );
}

useGLTF.preload("./Tree01.glb");
